In [9]:
import wrds

In [10]:
pip install wrds

Requirement already satisfied: wrds in /usr/local/sas/jupyterhub/prod/venvs/20210107/lib/python3.9/site-packages (3.0.8)
Requirement already satisfied: sqlalchemy in /usr/local/sas/jupyterhub/prod/venvs/20210107/lib/python3.9/site-packages (from wrds) (1.3.22)
Requirement already satisfied: psycopg2-binary in /usr/local/sas/jupyterhub/prod/venvs/20210107/lib/python3.9/site-packages (from wrds) (2.8.6)
Requirement already satisfied: pandas in /usr/local/sas/jupyterhub/prod/venvs/20210107/lib/python3.9/site-packages (from wrds) (1.2.0)
Requirement already satisfied: mock in /usr/local/sas/jupyterhub/prod/venvs/20210107/lib/python3.9/site-packages (from wrds) (4.0.3)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/sas/jupyterhub/prod/venvs/20210107/lib/python3.9/site-packages (from pandas->wrds) (1.19.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/sas/jupyterhub/prod/venvs/20210107/lib/python3.9/site-packages (from pandas->wrds) (2.8.1)
Requirement already satisfied: pytz>=2017.3 in /usr/local/sas/jupyterhub/prod/venvs/20210107/lib/python3.9/site-packages (from pandas->wrds) (2020.5)
Requirement already satisfied: six>=1.5 in /usr/local/sas/jupyterhub/prod/venvs/20210107/lib/python3.9/site-packages (from python-dateutil>=2.7.3->pandas->wrds) (1.15.0)
Note: you may need to restart the kernel to use updated packages.

In [11]:
db = wrds.Connection()

Enter your WRDS username [hmlim]: hmlim
Enter your password: ············

WRDS recommends setting up a .pgpass file.
You can find more info here:
https://www.postgresql.org/docs/9.5/static/libpq-pgpass.html.
Loading library list...
Done

In [12]:
db.list_libraries().sort()
db.list_libraries()

['aha',
 'aha_sample',
 'ahasamp',
 'audit',
 'audit_audit_comp',
 'audit_corp_legal',
 'bank',
 'blab',
 'block',
 'boardex',
 'boardex_trial',
 'boardsmp',
 'bvd',
 'bvdsamp',
 'calcbench_trial',
 'calcbnch',
 'cboe',
 'centris',
 'ciq',
 'ciq_common',
 'ciq_ratings',
 'ciq_ratings_new',
 'ciqsamp',
 'ciqsamp_common',
 'ciqsamp_keydev',
 'ciqsamp_transcripts',
 'cisdm',
 'cisdmsmp',
 'clrvt',
 'clrvtsmp',
 'comp',
 'comp_bank',
 'comp_bank_daily',
 'comp_execucomp',
 'comp_global',
 'comp_global_daily',
 'comp_ratings',
 'comp_segments_hist',
 'comp_segments_hist_daily',
 'compa',
 'compb',
 'compbd',
 'compdcur',
 'compg',
 'compgd',
 'comph',
 'compm',
 'compmcur',
 'compnad',
 'compsamp',
 'compsamp_snapshot',
 'compseg',
 'compsegd',
 'compsnap',
 'comscore',
 'contrib',
 'contrib_char_returns',
 'contrib_char_returns_new',
 'contrib_general',
 'contrib_general_new',
 'contrib_intangible_value',
 'contrib_kpss',
 'crsp',
 'crsp_a_ccm',
 'crsp_a_indexes',
 'crsp_a_stock',
 'crsp_q_indexes',
 'crsp_q_indexhist',
 'crsp_q_mutualfunds',
 'crspa',
 'crspm',
 'crspq',
 'crspsamp',
 'csmar',
 'csmar_financial',
 'csmar_funds',
 'csmar_trade',
 'dealscan',
 'djones',
 'dmef',
 'doe',
 'emdb',
 'etfg',
 'etfg_analytics',
 'etfg_constituents',
 'etfg_fund_flow',
 'etfg_industry',
 'etfg_samp',
 'etfgsamp',
 'eureka',
 'eurekahedge_sample',
 'evts',
 'execcomp',
 'factsamp_revere',
 'factset',
 'ff',
 'fisd',
 'fisdsamp',
 'fjc_linking',
 'fjc_litigation',
 'frb',
 'fssamp',
 'ftse',
 'ftsesamp',
 'ginsight',
 'gmi',
 'govpx',
 'govpxsmp',
 'gsi',
 'hbase_sample',
 'hbsamp',
 'hfr',
 'hfrsamp',
 'hfrsamp_hfrdb',
 'ibes',
 'ibescorp',
 'ibeskpi',
 'ifgr',
 'ifgrsamp',
 'ims',
 'ims_obp_trial',
 'imssamp',
 'infogroupsamp_business',
 'infogroupsamp_residential',
 'iri',
 'iss_issrecs',
 'iss_va_mf',
 'iss_va_shareholder',
 'iss_va_vote_global',
 'iss_va_vote_us',
 'issm',
 'kld',
 'ktmine',
 'ktmine_patents_samp',
 'ktsamp',
 'levin',
 'lspd',
 'lvnsamp',
 'macrofin',
 'macrofin_comm_trade',
 'macrofin_comm_trade_new',
 'markit',
 'mfl',
 'mrktsamp',
 'mrktsamp_cds',
 'mrktsamp_cdx',
 'mrktsamp_msf',
 'msfanly',
 'msfinst',
 'msrb',
 'msrbsamp',
 'nastraq',
 'omtrial',
 'optionm',
 'optionmsamp_europe',
 'optionmsamp_us',
 'otc',
 'otc_endofday',
 'pacap',
 'phlx',
 'ppublica',
 'ppubsamp',
 'ppubsamp_d4d',
 'ppubsamp_d4d_new',
 'preqin_pe',
 'preqin_pe_new',
 'preqin_vc',
 'preqsamp_all_new',
 'public',
 'pwt',
 'ravenpack_trial',
 'rent',
 'reprisk',
 'reprisk_sample',
 'repsamp',
 'revere',
 'risk',
 'risk_directors',
 'risk_governance',
 'risk_proposals',
 'risk_votes',
 'risksamp',
 'rpna',
 'rpnasamp',
 'sdc',
 'sdcsamp',
 'secsamp',
 'secsamp_all_new',
 'snapsamp',
 'snl',
 'snlsamp',
 'snlsamp_fig',
 'sprat',
 'sustain',
 'sustainalytics_all_new',
 'sustsamp',
 'taq',
 'taqm_2003',
 'taqm_2004',
 'taqm_2005',
 'taqm_2006',
 'taqm_2007',
 'taqm_2008',
 'taqm_2009',
 'taqm_2010',
 'taqm_2011',
 'taqm_2012',
 'taqm_2013',
 'taqm_2014',
 'taqm_2015',
 'taqm_2016',
 'taqm_2017',
 'taqm_2018',
 'taqmsamp',
 'taqmsec',
 'taqsamp',
 'tass',
 'tfn',
 'totalq',
 'toyo',
 'tr_13f',
 'tr_dealscan',
 'tr_ds',
 'tr_ibes',
 'tr_ibes_guidance',
 'tr_ibes_iga',
 'tr_ibeskpi',
 'tr_ibeskpi_new',
 'tr_insiders',
 'tr_mutualfunds',
 'tr_ownership',
 'trace',
 'trace_enhanced',
 'trace_standard',
 'trown',
 'trsamp',
 'trsdcgs',
 'trws',
 'twoiq',
 'twoiq_samp',
 'twoiqsmp',
 'wcai',
 'wqa',
 'wrds_lib_internal',
 'wrdsapps',
 'wrdsapps_eushort',
 'wrdsapps_eushort_new',
 'wrdsapps_patents',
 'wrdsapps_patents_new',
 'wrdsrpts',
 'wrdsrpts_rep_usage',
 'wrdssec',
 'wrdssec_common',
 'wrdssec_insiders',
 'wrdssec_midas',
 'wrdssec_secsa',
 'zacks',
 'zacksamp']

In [5]:
db.list_tables(library='comp')

['aco_amda',
 'aco_imda',
 'aco_indfnta',
 'aco_indfntq',
 'aco_indfntytd',
 'aco_indsta',
 'aco_indstq',
 'aco_indstytd',
 'aco_notesa',
 'aco_notesq',
 'aco_notessa',
 'aco_notesytd',
 'aco_pnfnda',
 'aco_pnfndq',
 'aco_pnfndytd',
 'aco_pnfnta',
 'aco_pnfntq',
 'aco_pnfntytd',
 'aco_transa',
 'aco_transq',
 'aco_transsa',
 'aco_transytd',
 'adsprate',
 'asec_amda',
 'asec_imda',
 'asec_notesa',
 'asec_notesq',
 'asec_transa',
 'asec_transq',
 'bank_aacctchg',
 'bank_adesind',
 'bank_afnd1',
 'bank_afnd2',
 'bank_afnddc1',
 'bank_afnddc2',
 'bank_afntind',
 'bank_funda',
 'bank_funda_fncd',
 'bank_fundq',
 'bank_fundq_fncd',
 'bank_iacctchg',
 'bank_idesind',
 'bank_ifndq',
 'bank_ifndytd',
 'bank_ifntq',
 'bank_ifntytd',
 'bank_names',
 'bank_namesq',
 'chars',
 'co_aacctchg',
 'co_aaudit',
 'co_adesind',
 'co_adjfact',
 'co_afnd1',
 'co_afnd2',
 'co_afnddc1',
 'co_afnddc2',
 'co_afntind1',
 'co_afntind2',
 'co_ainvval',
 'co_amkt',
 'co_busdescl',
 'co_cotype',
 'co_filedate',
 'co_fortune',
 'co_hgic',
 'co_iacctchg',
 'co_iaudit',
 'co_idesind',
 'co_ifndq',
 'co_ifndsa',
 'co_ifndytd',
 'co_ifntq',
 'co_ifntsa',
 'co_ifntytd',
 'co_imkt',
 'co_industry',
 'co_ipcd',
 'co_mthly',
 'co_offtitl',
 'company',
 'currency',
 'dd_group',
 'dd_group_xref',
 'dd_item',
 'dd_package',
 'ecind_desc',
 'ecind_mth',
 'exrt_dly',
 'exrt_mth',
 'filings',
 'funda',
 'funda_fncd',
 'fundq',
 'fundq_fncd',
 'g_chars',
 'g_co_aaudit',
 'g_co_adesind',
 'g_co_afnd1',
 'g_co_afnd2',
 'g_co_afnddc1',
 'g_co_afnddc2',
 'g_co_afntind1',
 'g_co_afntind2',
 'g_co_ainvval',
 'g_co_hgic',
 'g_co_iaudit',
 'g_co_idesind',
 'g_co_ifndq',
 'g_co_ifndsa',
 'g_co_ifndytd',
 'g_co_ifntq',
 'g_co_ifntsa',
 'g_co_ifntytd',
 'g_co_industry',
 'g_co_ipcd',
 'g_co_offtitl',
 'g_company',
 'g_currency',
 'g_ecind_desc',
 'g_ecind_mth',
 'g_exrt_dly',
 'g_exrt_mth',
 'g_funda',
 'g_funda_fncd',
 'g_fundq',
 'g_fundq_fncd',
 'g_idx_daily',
 'g_idx_index',
 'g_idx_mth',
 'g_idxcst_his',
 'g_names',
 'g_names_ix',
 'g_names_ix_cst',
 'g_namesq',
 'g_sec_adesind',
 'g_sec_adjfact',
 'g_sec_afnd',
 'g_sec_afnddc',
 'g_sec_afnt',
 'g_sec_divid',
 'g_sec_dprc',
 'g_sec_dtrt',
 'g_sec_history',
 'g_sec_idesind',
 'g_sec_ifnd',
 'g_sec_ifnt',
 'g_sec_split',
 'g_secd',
 'g_secnamesd',
 'g_security',
 'g_sedolgvkey',
 'g_tmptable_pkg6153_tbl4023',
 'idx_ann',
 'idx_anndes',
 'idx_daily',
 'idx_index',
 'idx_mth',
 'idx_qrt',
 'idx_qrtdes',
 'idxcst_his',
 'io_qaggregate',
 'io_qbuysell',
 'io_qchanges',
 'io_qfloatadj',
 'io_qholders',
 'it_mbuysell',
 'it_msummary',
 'it_r_rltn',
 'names',
 'names_aco_indsta',
 'names_aco_indstq',
 'names_aco_pnfnda',
 'names_aco_pnfndq',
 'names_adsprate',
 'names_ix',
 'names_ix_cst',
 'names_seg',
 'namesd',
 'namesm',
 'namesq',
 'r_accstd',
 'r_acqmeth',
 'r_auditors',
 'r_auopic',
 'r_balpres',
 'r_cf_formt',
 'r_co_status',
 'r_coindpre',
 'r_compstat',
 'r_consol',
 'r_country',
 'r_cstclscd',
 'r_datacode',
 'r_datafmt',
 'r_divtaxmarker',
 'r_docsrce',
 'r_ex_codes',
 'r_exchgtier',
 'r_exrt_typ',
 'r_fndfntcd',
 'r_footnts',
 'r_foricd',
 'r_giccd',
 'r_hcalendr',
 'r_idxclscd',
 'r_inactvcd',
 'r_incstats',
 'r_indfmt',
 'r_indsec',
 'r_invval',
 'r_issuetyp',
 'r_majidxcl',
 'r_mic_codes',
 'r_naiccd',
 'r_notetype',
 'r_ntsubtype',
 'r_offcrso',
 'r_ogmethod',
 'r_opinions',
 'r_prc_stat',
 'r_qsrcdoc',
 'r_sec_stat',
 'r_secannfn',
 'r_sectors',
 'r_siccd',
 'r_spiicd',
 'r_spmicd',
 'r_statalrt',
 'r_states',
 'r_stko',
 'r_titles',
 'r_updates',
 'sec_adesind',
 'sec_adjfact',
 'sec_afnd',
 'sec_afnddc',
 'sec_afnt',
 'sec_divid',
 'sec_dprc',
 'sec_dtrt',
 'sec_history',
 'sec_idesind',
 'sec_ifnd',
 'sec_ifnt',
 'sec_mdivfn',
 'sec_mshare',
 'sec_msptfn',
 'sec_mth',
 'sec_mthdiv',
 'sec_mthprc',
 'sec_mthspt',
 'sec_mthtrt',
 'sec_shortint',
 'sec_spind',
 'sec_split',
 'secd',
 'secm',
 'security',
 'sedolgvkey',
 'seg_ann',
 'seg_annfund',
 'seg_customer',
 'seg_geo',
 'seg_naics',
 'seg_product',
 'seg_type',
 'spidx_cst',
 'spind',
 'spind_dly',
 'spind_mth',
 'tmptable_pkg6153_tbl4023',
 'wrds_seg_customer',
 'wrds_seg_geo',
 'wrds_seg_product',
 'wrds_segmerged',
 'xfl_column',
 'xfl_table']

In [6]:
db.list_tables('comp')

['aco_amda',
 'aco_imda',
 'aco_indfnta',
 'aco_indfntq',
 'aco_indfntytd',
 'aco_indsta',
 'aco_indstq',
 'aco_indstytd',
 'aco_notesa',
 'aco_notesq',
 'aco_notessa',
 'aco_notesytd',
 'aco_pnfnda',
 'aco_pnfndq',
 'aco_pnfndytd',
 'aco_pnfnta',
 'aco_pnfntq',
 'aco_pnfntytd',
 'aco_transa',
 'aco_transq',
 'aco_transsa',
 'aco_transytd',
 'adsprate',
 'asec_amda',
 'asec_imda',
 'asec_notesa',
 'asec_notesq',
 'asec_transa',
 'asec_transq',
 'bank_aacctchg',
 'bank_adesind',
 'bank_afnd1',
 'bank_afnd2',
 'bank_afnddc1',
 'bank_afnddc2',
 'bank_afntind',
 'bank_funda',
 'bank_funda_fncd',
 'bank_fundq',
 'bank_fundq_fncd',
 'bank_iacctchg',
 'bank_idesind',
 'bank_ifndq',
 'bank_ifndytd',
 'bank_ifntq',
 'bank_ifntytd',
 'bank_names',
 'bank_namesq',
 'chars',
 'co_aacctchg',
 'co_aaudit',
 'co_adesind',
 'co_adjfact',
 'co_afnd1',
 'co_afnd2',
 'co_afnddc1',
 'co_afnddc2',
 'co_afntind1',
 'co_afntind2',
 'co_ainvval',
 'co_amkt',
 'co_busdescl',
 'co_cotype',
 'co_filedate',
 'co_fortune',
 'co_hgic',
 'co_iacctchg',
 'co_iaudit',
 'co_idesind',
 'co_ifndq',
 'co_ifndsa',
 'co_ifndytd',
 'co_ifntq',
 'co_ifntsa',
 'co_ifntytd',
 'co_imkt',
 'co_industry',
 'co_ipcd',
 'co_mthly',
 'co_offtitl',
 'company',
 'currency',
 'dd_group',
 'dd_group_xref',
 'dd_item',
 'dd_package',
 'ecind_desc',
 'ecind_mth',
 'exrt_dly',
 'exrt_mth',
 'filings',
 'funda',
 'funda_fncd',
 'fundq',
 'fundq_fncd',
 'g_chars',
 'g_co_aaudit',
 'g_co_adesind',
 'g_co_afnd1',
 'g_co_afnd2',
 'g_co_afnddc1',
 'g_co_afnddc2',
 'g_co_afntind1',
 'g_co_afntind2',
 'g_co_ainvval',
 'g_co_hgic',
 'g_co_iaudit',
 'g_co_idesind',
 'g_co_ifndq',
 'g_co_ifndsa',
 'g_co_ifndytd',
 'g_co_ifntq',
 'g_co_ifntsa',
 'g_co_ifntytd',
 'g_co_industry',
 'g_co_ipcd',
 'g_co_offtitl',
 'g_company',
 'g_currency',
 'g_ecind_desc',
 'g_ecind_mth',
 'g_exrt_dly',
 'g_exrt_mth',
 'g_funda',
 'g_funda_fncd',
 'g_fundq',
 'g_fundq_fncd',
 'g_idx_daily',
 'g_idx_index',
 'g_idx_mth',
 'g_idxcst_his',
 'g_names',
 'g_names_ix',
 'g_names_ix_cst',
 'g_namesq',
 'g_sec_adesind',
 'g_sec_adjfact',
 'g_sec_afnd',
 'g_sec_afnddc',
 'g_sec_afnt',
 'g_sec_divid',
 'g_sec_dprc',
 'g_sec_dtrt',
 'g_sec_history',
 'g_sec_idesind',
 'g_sec_ifnd',
 'g_sec_ifnt',
 'g_sec_split',
 'g_secd',
 'g_secnamesd',
 'g_security',
 'g_sedolgvkey',
 'g_tmptable_pkg6153_tbl4023',
 'idx_ann',
 'idx_anndes',
 'idx_daily',
 'idx_index',
 'idx_mth',
 'idx_qrt',
 'idx_qrtdes',
 'idxcst_his',
 'io_qaggregate',
 'io_qbuysell',
 'io_qchanges',
 'io_qfloatadj',
 'io_qholders',
 'it_mbuysell',
 'it_msummary',
 'it_r_rltn',
 'names',
 'names_aco_indsta',
 'names_aco_indstq',
 'names_aco_pnfnda',
 'names_aco_pnfndq',
 'names_adsprate',
 'names_ix',
 'names_ix_cst',
 'names_seg',
 'namesd',
 'namesm',
 'namesq',
 'r_accstd',
 'r_acqmeth',
 'r_auditors',
 'r_auopic',
 'r_balpres',
 'r_cf_formt',
 'r_co_status',
 'r_coindpre',
 'r_compstat',
 'r_consol',
 'r_country',
 'r_cstclscd',
 'r_datacode',
 'r_datafmt',
 'r_divtaxmarker',
 'r_docsrce',
 'r_ex_codes',
 'r_exchgtier',
 'r_exrt_typ',
 'r_fndfntcd',
 'r_footnts',
 'r_foricd',
 'r_giccd',
 'r_hcalendr',
 'r_idxclscd',
 'r_inactvcd',
 'r_incstats',
 'r_indfmt',
 'r_indsec',
 'r_invval',
 'r_issuetyp',
 'r_majidxcl',
 'r_mic_codes',
 'r_naiccd',
 'r_notetype',
 'r_ntsubtype',
 'r_offcrso',
 'r_ogmethod',
 'r_opinions',
 'r_prc_stat',
 'r_qsrcdoc',
 'r_sec_stat',
 'r_secannfn',
 'r_sectors',
 'r_siccd',
 'r_spiicd',
 'r_spmicd',
 'r_statalrt',
 'r_states',
 'r_stko',
 'r_titles',
 'r_updates',
 'sec_adesind',
 'sec_adjfact',
 'sec_afnd',
 'sec_afnddc',
 'sec_afnt',
 'sec_divid',
 'sec_dprc',
 'sec_dtrt',
 'sec_history',
 'sec_idesind',
 'sec_ifnd',
 'sec_ifnt',
 'sec_mdivfn',
 'sec_mshare',
 'sec_msptfn',
 'sec_mth',
 'sec_mthdiv',
 'sec_mthprc',
 'sec_mthspt',
 'sec_mthtrt',
 'sec_shortint',
 'sec_spind',
 'sec_split',
 'secd',
 'secm',
 'security',
 'sedolgvkey',
 'seg_ann',
 'seg_annfund',
 'seg_customer',
 'seg_geo',
 'seg_naics',
 'seg_product',
 'seg_type',
 'spidx_cst',
 'spind',
 'spind_dly',
 'spind_mth',
 'tmptable_pkg6153_tbl4023',
 'wrds_seg_customer',
 'wrds_seg_geo',
 'wrds_seg_product',
 'wrds_segmerged',
 'xfl_column',
 'xfl_table']

In [2]:
db.describe_table('comp', 'company')

NameError: name 'db' is not defined

In [8]:
db.get_table('comp', 'company', obs=100)

,conm,gvkey,add1,add2,add3,add4,addzip,busdesc,cik,city,...,priusa,sic,spcindcd,spcseccd,spcsrc,state,stko,weburl,dldte,ipodate
0,A & E PLASTIK PAK INC,001000,None,None,None,None,None,None,None,None,...,01,3089,325.0,978.0,None,None,0.0,None,1978-06-30,None
1,A & M FOOD SERVICES INC,001001,1924 South Utica Avenue,None,None,None,94104,None,0000723576,Tulsa,...,01,5812,420.0,978.0,None,OK,0.0,None,1986-07-31,None
2,AAI CORP,001002,124 Industry Lane,None,None,None,21030-0126,"AAI Corporation, together with its subsidiarie...",0000001745,Hunt Valley,...,01,3825,230.0,940.0,None,MD,0.0,None,1977-03-31,None
3,A.A. IMPORTING CO INC,001003,7700 Hall Street,None,None,None,63125,"A.A. Importing Company, Inc. designs, manufact...",0000730052,St. Louis,...,01,5712,449.0,976.0,None,MO,3.0,www.aaimporting.com,1992-04-30,None
4,AAR CORP,001004,"One AAR Place, 1100 North Wood Dale Road",None,None,None,60191,AAR Corp. provides products and services to co...,0000001750,Wood Dale,...,01,5080,110.0,925.0,B,IL,0.0,www.aarcorp.com,None,1988-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,ACETO CORP,001094,4 Tri Harbor Court,None,None,None,11050,"Aceto Corporation engages in the development, ...",0000002034,Port Washington,...,01,5160,160.0,970.0,D,NY,3.0,www.aceto.com,2019-10-02,None
96,ACKERLEY GROUP INC,001095,"1301 5th Avenue, Suite 4000",None,None,None,98101,"As of June 14, 2002, The Ackerley Group, Inc. ...",0000319120,Seattle,...,01,4833,150.0,978.0,B-,WA,0.0,None,2002-06-17,None
97,MORGUARD CORP,001096,"55 City Centre Drive, Suite 800",None,None,None,L5B 1M3,"Morguard Corporation, a real estate investment...",None,Mississauga,...,01,6500,850.0,800.0,B,ON,0.0,www.morguard.com,None,None
98,ACMAT CORP -CL A,001097,30 South Road,None,None,None,06032,"ACMAT Corporation, through its subsidiary, ACS...",0000002062,Farmington,...,02,6351,240.0,925.0,B,CT,3.0,www.acmatcorp.com,None,None
99,ACME-CLEVELAND CORP,001098,"30100 Chagrin Boulevard, Suite 100",None,None,None,44124-5705,Acme-Cleveland Corporation is engaged in the m...,0000869676,Pepper Pike,...,01,3661,180.0,940.0,None,OH,0.0,None,1996-07-31,None

In [13]:
db.get_table('comp', 'company', columns=['gvkey'], obs=100 )

     gvkey
0   001000
1   001001
2   001002
3   001003
4   001004
..     ...
95  001094
96  001095
97  001096
98  001097
99  001098

[100 rows x 1 columns]

In [16]:
# Select one stock's monthly price
# from 2019 onwards

apple = db.raw_sql("""select permno, date, prc, ret, shrout 
                        from crsp.msf 
                        where permno = 14593
                        and date>='01/01/2019'""", 
                     date_cols=['date'])

apple

     permno       date         prc       ret      shrout
0   14593.0 2019-01-31  166.440002  0.055154   4715280.0
1   14593.0 2019-02-28  173.149994  0.044701   4715280.0
2   14593.0 2019-03-29  189.949997  0.097026   4715280.0
3   14593.0 2019-04-30  200.669998  0.056436   4601075.0
4   14593.0 2019-05-31  175.070007 -0.123735   4601075.0
5   14593.0 2019-06-28  197.919998  0.130519   4531395.0
6   14593.0 2019-07-31  213.039993  0.076394   4519180.0
7   14593.0 2019-08-30  208.740005 -0.016570   4519180.0
8   14593.0 2019-09-30  223.970001  0.072962   4443236.0
9   14593.0 2019-10-31  248.759995  0.110684   4443265.0
10  14593.0 2019-11-29  267.250000  0.077424   4443265.0
11  14593.0 2019-12-31  293.649994  0.098784   4384959.0
12  14593.0 2020-01-31  309.510010  0.054010   4375480.0
13  14593.0 2020-02-28  273.359985 -0.114310   4375480.0
14  14593.0 2020-03-31  254.289993 -0.069761   4323987.0
15  14593.0 2020-04-30  293.799988  0.155374   4334335.0
16  14593.0 2020-05-29  317.940002  0.084956   4334335.0
17  14593.0 2020-06-30  364.799988  0.147386   4283939.0
18  14593.0 2020-07-31  425.040009  0.165132   4275634.0
19  14593.0 2020-08-31  129.039993  0.216309  17102536.0
20  14593.0 2020-09-30  115.809998 -0.102526  16976763.0
21  14593.0 2020-10-30  108.860001 -0.060012  17001802.0
22  14593.0 2020-11-30  119.050003  0.095490  17001802.0
23  14593.0 2020-12-31  132.690002  0.114574  17001802.0

In [17]:
apple.dtypes

permno           float64
date      datetime64[ns]
prc              float64
ret              float64
shrout           float64
dtype: object

In [18]:
apple_fund = db.raw_sql("""select a.gvkey, a.iid, a.datadate, a.tic, a.conm,
                            a.at, b.prccm, b.cshoq 
                            
                            from comp.funda a 
                            inner join comp.secm b 
                            
                            on a.gvkey = b.gvkey
                            and a.iid = b.iid
                            and a.datadate = b.datadate
                        
                            where a.tic = 'AAPL' 
                            and a.datadate>='01/01/2010'
                            and a.datafmt = 'STD' 
                            and a.consol = 'C' 
                            and a.indfmt = 'INDL'
                            """, date_cols=['datadate'])

apple_fund.shape

(11, 8)

In [20]:
apple_fund

     gvkey iid   datadate   tic       conm        at    prccm      cshoq
0   001690  01 2010-09-30  AAPL  APPLE INC   75183.0  283.750    915.970
1   001690  01 2011-09-30  AAPL  APPLE INC  116371.0  381.320    929.277
2   001690  01 2012-09-30  AAPL  APPLE INC  176064.0  667.105    939.208
3   001690  01 2013-09-30  AAPL  APPLE INC  207000.0  476.750    899.213
4   001690  01 2014-09-30  AAPL  APPLE INC  231839.0  100.750   5866.161
5   001690  01 2015-09-30  AAPL  APPLE INC  290479.0  110.300   5578.753
6   001690  01 2016-09-30  AAPL  APPLE INC  321686.0  113.050   5336.166
7   001690  01 2017-09-30  AAPL  APPLE INC  375319.0  154.120   5126.201
8   001690  01 2018-09-30  AAPL  APPLE INC  365725.0  225.740   4754.986
9   001690  01 2019-09-30  AAPL  APPLE INC  338516.0  223.970   4443.236
10  001690  01 2020-09-30  AAPL  APPLE INC  323888.0  115.810  16976.763

In [10]:
pip install matplotlib

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x2abe27ce4670>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /simple/matplotlib/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x2abe27ce4880>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /simple/matplotlib/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x2abe27ce4a30>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /simple/matplotlib/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x2abe27ce4be0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /simple/matplotlib/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x2abe27ce4d90>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /simple/matplotlib/
ERROR: Could not find a version that satisfies the requirement matplotlib
ERROR: No matching distribution found for matplotlib
Note: you may need to restart the kernel to use updated packages.

In [14]:
db.list_libraries().sort()

In [1]:
type(db.list_libraries())

NameError: name 'db' is not defined